---

- name: Generate a report of COTS tools used for this build
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - name: Set the csv filename
      set_fact:
        cots_csv_file: "/tmp/cots_report.csv"

    - name: Set the apt repo URL
      ansible.builtin.uri:
        url: "https://snapshot.debian.org/archive/debian/{{ apt_snapshot_date }}"
        return_content: no
        follow_redirects: all
      register: apt_url

    - name: Create the combined list
      set_fact:
        combined_packages: "{{ all_packages + tpm_packages }}"

    - name: Dedupe the list
      set_fact:
        deduped_packages: "{{ combined_packages | unique | select | list }}"

    - name: Get the filename in the apt repo
      ansible.builtin.shell:
        cmd: >
          apt-cache show {{ item }} | grep "Filename" | 
          cut -d' ' -f2
      loop: "{{ deduped_packages }}"
      register: apt_filenames

    - name: Get the SHA256 hash
      ansible.builtin.shell:
        cmd: >
          apt-cache show {{ item }} | grep "SHA256" | 
          cut -d' ' -f2
      loop: "{{ deduped_packages }}"
      register: apt_checksums

    - name: Print COTS for apt packages
      ansible.builtin.shell:
        cmd: >
          echo "{{ apt_url.url }}{{ item.1.stdout }},{{ item.1.stdout | split('/') | last }},{{ item.0 | split('=') | last }},DATE,{{ item.2.stdout }}" >> {{ cots_csv_file }}
      loop: "{{ deduped_packages | zip(apt_filenames.results, apt_checksums.results) | list }}"

    - name: Determine system architecture for appropriate Rust install
      set_fact: 
        architecture: "{{ 'aarch64' if (ansible_architecture == 'aarch64' or ansible_architecture == 'arm64') else 'x86_64' if (ansible_architecture == 'x86_64') else 'unsupported' }}"

    - name: Define Rust tarball name
      set_fact: 
        rust_tarball: "rust-{{ rust_version }}-{{ architecture }}-unknown-linux-gnu.tar.gz"

    - name: Define the URL to download the appropriate Rust tarball
      set_fact:
        rust_tarball_url: "https://static.rust-lang.org/dist/{{ rust_tarball }}"

    - name: Define Rust manifest name
      set_fact: 
        rust_manifest: "channel-rust-{{ rust_version }}.toml"

    - name: Define URL to Rust channel manifest for this version
      set_fact:
        rust_manifest_url: "https://static.rust-lang.org/dist/{{ rust_manifest }}"

    - name: Download Rust channel manifest for this version
      ansible.builtin.get_url:
        url: "{{ rust_manifest_url }}"
        dest: "/tmp/{{ rust_manifest }}"

    - name: Find the sha256 hash for our version
      ansible.builtin.shell:
        cmd: "grep -A1 {{ rust_tarball }} /tmp/{{ rust_manifest }} | grep hash | cut -d'=' -f2 | xargs"
      register: rust_checksum_from_manifest

    - name: Add Rust to COTS report
      ansible.builtin.shell:
        cmd: >
          echo "{{ rust_tarball_url }},{{ rust_tarball }},{{ rust_version }},DATE,{{ rust_checksum_from_manifest.stdout }}" >> {{ cots_csv_file }}
