---

- name: Generate a report of COTS tools used for this build
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - name: De-dupe the list for efficiency
      set_fact:
        all_packages: "{{ all_packages | unique | select | list }}"

    - name: De-dupe the TPM list for efficiency
      set_fact:
        tpm_packages: "{{ tpm_packages | unique | select | list }}"

    - name: Get the filename in the apt repo
      ansible.builtin.shell:
        cmd: >
          apt-cache show {{ item }} | grep "Filename" | 
          cut -d' ' -f2
      loop: "{{ all_packages + tpm_packages }}"
      register: apt_filenames

    - name: Get the SHA256 hash
      ansible.builtin.shell:
        cmd: >
          apt-cache show {{ item }} | grep "SHA256" | 
          cut -d' ' -f2
      loop: "{{ all_packages + tpm_packages }}"
      register: apt_checksums

    - name: Print files and checksums
      debug:
        msg: "{{ item.0 }} = {{ item.1 }}"
      loop: "{{ apt_filenames | zip(apt_checksums) | list }}"

