---

- name: Generate a report of COTS tools used for this build
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - name: Set the apt repo URL
      ansible.builtin.uri:
        url: "https://snapshot.debian.org/archive/debian/{{ apt_snapshot_date }}"
        return_content: no
        follow_redirects: all
      register: apt_url

    - name: Create the combined list
        set_fact:
          deduped_packages: "{{ all_packages + tpm_packages | unique | select | list }}"

    - name: Get the filename in the apt repo
      ansible.builtin.shell:
        cmd: >
          apt-cache show {{ item }} | grep "Filename" | 
          cut -d' ' -f2
      loop: "{{ deduped_packages }}"
      register: apt_filenames

    - name: Get the SHA256 hash
      ansible.builtin.shell:
        cmd: >
          apt-cache show {{ item }} | grep "SHA256" | 
          cut -d' ' -f2
      loop: "{{ deduped_packages }}"
      register: apt_checksums

    - name: Print COTS for apt packages
      debug:
        msg: "{{ apt_url.url }}{{ item.1.stdout }},{{ item.0 }},{{ item.0.stdout | split('=') | last }},DATE,{{ item.2.stdout }}"
      loop: "{{ deduped_packages | zip(apt_filenames.results, apt_checksums.results) | list }}"

