---

- name: Generate a report of COTS tools used for this build
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - name: Set the apt repo URL
      ansible.builtin.uri:
        url: "https://snapshot.debian.org/archive/debian/{{ apt_snapshot_date }}"
        return_content: no
        follow_redirects: all
      register: apt_url

    - name: De-dupe the list for efficiency
      set_fact:
        all_packages: "{{ all_packages | unique | select | list }}"

    - name: De-dupe the TPM list for efficiency
      set_fact:
        tpm_packages: "{{ tpm_packages | unique | select | list }}"

    - name: Get the filename in the apt repo
      ansible.builtin.shell:
        cmd: >
          apt-cache show {{ item }} | grep "Filename" | 
          cut -d' ' -f2
      loop: "{{ all_packages + tpm_packages }}"
      register: apt_filenames

    - name: Get the SHA256 hash
      ansible.builtin.shell:
        cmd: >
          apt-cache show {{ item }} | grep "SHA256" | 
          cut -d' ' -f2
      loop: "{{ all_packages + tpm_packages }}"
      register: apt_checksums

    - name: Print COTS for apt packages
      debug:
        msg: "{{ apt_url.url }}{{ item.0.stdout }},{{ item.0.stdout }},{{ item.0.stdout | split('=') | last }},DATE,{{ item.1.stdout }}"
      loop: "{{ apt_filenames.results | zip(apt_checksums.results) | list }}"

