---

- name: Install system level dependencies used by various apps and services
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - name: De-dupe the list for efficiency
      set_fact:
        all_packages: "{{ all_packages | unique | select | list }}"

    - name: Get the latest available version of each package
      ansible.builtin.shell:
        cmd: >
          apt-cache madison {{ item | split('=') | first }} | grep "Packages" |
          awk '{print $1"="$3}'
      loop: "{{ all_packages }}"
      register: versions

    - name: Print to tmp file
      ansible.builtin.shell:
        cmd: "echo {{ item.stdout | quote }} >> /tmp/versions"
      loop: "{{ versions.results }}"

