---

#-- This is expected to run on a clean system
#-- Dependencies are then pulled in correctly
#-- If on an existing system, this can break if 
#-- a dependency is already installed
#-- TODO: Make it work on pre-existing systems???
- name: Download the packages and dependencies
  ansible.builtin.command:
    cmd: "apt-get install --reinstall --no-install-recommends --download-only -y {{ item }}"
  with_items:
    - "{{ all_packages }}"
