---

- import_tasks: download_only.yaml
  tags:
    - online

- name: Install the packages (single)
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: false
    allow_downgrades: true
    state: present
  with_items:
    - "{{ all_packages }}"
  when: (batch_package_install is not defined) or (batch_package_install is false)
  tags:
    - offline

- name: Install the packages (batch)
  ansible.builtin.command:
    cmd: "apt-get -y --allow-downgrades --no-install-recommends install {{ all_packages | join(' ') }}"
  when: (batch_package_install is defined) and (batch_package_install is true)
  tags:
    - offline
