---

- import_tasks: download_only.yaml
  tags:
    - online

- name: Install the packages
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: false
    state: present
  with_items:
    - "{{ all_packages }}"
  tags:
    - offline

