---

- name: Configure an ethernet port if available
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:

    - name: Copy the avahi-autoipd systemd service into place
      ansible.builtin.copy:
        src: "files/avahi-autoipd.service"
        dest: "/etc/systemd/system/avahi-autoipd@.service"

    - name: Ensure a systemctl daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true
