---

- name: Install Brother printer drivers
  hosts: 127.0.0.1
  connection: local
  become: true

  vars:
    brother_32bit_packages:
      - libc6:i386
      - libncurses5:i386
      - libstdc++6:i386

    brother_printer_driver_urls:
      - "https://download.brother.com/welcome/dlfp100949/pj822pdrv-1.2.0-1.i386.deb"
      - "https://download.brother.com/welcome/dlfp100952/pj823pdrv-1.2.0-1.i386.deb"

  tasks:
    - import_tasks: shared_tasks/user_to_configure.yaml
    - import_tasks: shared_tasks/well_known_paths.yaml

    - name: Ensure we don't carry over any packages from other tasks
      set_fact:
        all_packages: []

    - name: Create a list of all the packages we need
      set_fact:
        all_packages: "{{ all_packages | default([]) + [ item ] }}"
      with_items:
        - "{{ brother_32bit_packages | default([]) }}"

    #-- Does this need to run offline too?
    - name: Add 32-bit binary support
      ansible.builtin.command: "dpkg --add-architecture i386"
      tags:
        - online

    - name: Update apt sources for 32-bit binary support
      ansible.builtin.apt:
        update_cache: true
      tags:
        - online

    - name: Import the apt role which supports online and offline builds
      ansible.builtin.import_role:
        name: apt

    #-- We have the i386 packages installed at this point
    #-- Now we handle the drivers directly

    - name: Download the Brother printer drivers
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: "/var/cache/apt/archives/"
      loop: "{{ brother_printer_driver_urls }}"
      tags:
        - online

    - name: Install Brother printer drivers directly
      ansible.builtin.shell:
        cmd: "dpkg -i /var/cache/apt/archives/{{ item | split('/') | last }}"
      with_items:
        - "{{ brother_printer_driver_urls }}"
      tags:
        - offline

    - name: Remove printer configs that interfere with our config
      ansible.builtin.command: "lpadmin -x {{ item }}"
      loop:
        - "PJ-822"
        - "PJ-823"
      tags:
        - offline
