---

- name: Configure NetworkManager to work in locked down images
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - name: Copy /etc/resolv.conf to /var/lib/dhcp
      ansible.builtin.copy:
        src: "/etc/resolv.conf"
        dest: "/var/lib/dhcp/resolv.conf"
        remote_src: yes
        mode: preserve

    - name: Make /etc/resolv.conf a symlink
      ansible.builtin.file:
        path: "/etc/resolv.conf"
        src: "/var/lib/dhcp/resolv.conf"
        state: "link"
        force: true

    - name: Add NetworkManager config to update resolv.conf
      ansible.builtin.lineinfile:
        path: "/etc/NetworkManager/NetworkManager.conf"
        line: "rc-manager=file"
        insertafter: '\[main\]'

