---

#Driver: files/libNPrint.so.2.9
#
- name: Install CACvote Nippon Label Printer Driver 
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:

    - name: Define printer driver
      set_fact:
        label_printer_driver: "files/libNPrint.so.2.9"

    - name: Install the driver
      ansible.builtin.copy:
        src: "{{ label_printer_driver }}"
        dest: "/usr/lib/"

    - name: Update potential library dependencies for the driver
      ansible.builtin.command: "/usr/sbin/ldconfig"

    - name: Manually add a symlink needed for the library
      ansible.builtin.file:
        dest: "/usr/lib/libNPrint.so"
        src: "/usr/lib/libNPrint.so.2"
        state: link

    - name: Create the NPI directory and set permissions
      ansible.builtin.file:
        path: "/usr/npi"
        state: directory
        owner: lp
        group: lp
        mode: 0777
