---
- name: All the cacvote system level build steps
  hosts: 127.0.0.1
  connection: local
  become: yes

- import_playbook: packages.yaml
- import_playbook: initialize_encrypted_volumes.yaml
- import_playbook: node.yaml
- import_playbook: rust.yaml
- import_playbook: rust_targets.yaml
- import_playbook: rubygems.yaml
- import_playbook: repos.yaml
#- import_playbook: cacvote_label_printer.yaml
#- import_playbook: brother_printers.yaml
- import_playbook: logrotate.yaml
- import_playbook: cacvote_network_manager.yaml
- import_playbook: disable_services.yaml
