---

- name: Install Dev Packages on a QA Image
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - import_tasks: shared_tasks/user_to_configure.yaml
    - import_tasks: shared_tasks/well_known_paths.yaml

    - name: Ensure we don't carry over any packages from other tasks
      set_fact:
        all_packages: []

    - name: Create a list of all the packages we need
      set_fact:
        all_packages: "{{ all_packages | default([]) + [ item ] }}"
      with_items:
        - "{{ dev_packages | default([]) }}"
      when:
        - (qa_image is defined) and (qa_image is true) and (dev_packages is defined)

    - name: Import the apt role which supports online and offline builds
      ansible.builtin.import_role:
        name: apt
      tags:
        - online

