---
- name: Disable unneeded system services 
  hosts: 127.0.0.1
  connection: local
  become: true

  vars:
    services_to_disable: []

  tasks:

    - name: Disable system services 
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop: "{{ services_to_disable | default([]) }}"
