---
#-- Note: The {{ device }} var will be defined after this runs
- ansible.builtin.import_playbook: partition_tb_usb.yaml

- name: Prepare USB and export 
  hosts: 127.0.0.1
  connection: local
  become: true  

  vars:
    user_to_configure: "{{ ansible_env.SUDO_USER | default('root') }}"

  tasks:
    
    - name: Define well-known paths
      set_fact: 
        well_known_paths:
          apt_packages:
            system_path: "/var/cache/apt/archives"
            usb_path: "apt_packages"
          tools:
            system_path: "/tmp/downloads"
            usb_path: "downloads"
          vxsuite-complete-system:
            system_path: "~{{ user_to_configure }}/code/vxsuite-complete-system"
            usb_path: "vxsuite-complete-system"
    
    - name: Get the USB mountpoint
      ansible.builtin.command: lsblk -no mountpoint "/dev/{{ device }}1"
      register: usb_mnt
    
    - name: Copy the files to the USB
      ansible.builtin.copy:
        src: "{{ item.value.system_path }}/"
        dest: "{{ usb_mnt.stdout }}/{{ item.value.usb_path }}/"
        remote_src: true
      with_dict:
        - "{{ well_known_paths }}"
    
    - name: Sync the USB to ensure all data has been written (May take a few minutes)
      ansible.builtin.command: /usr/bin/sync

