---
#-- Note: The {{ device }} var will be defined after this runs
- ansible.builtin.import_playbook: partition_tb_usb.yaml

- name: Prepare USB and export 
  hosts: 127.0.0.1
  connection: local
  become: true  

  tasks:
    
    - import_tasks: shared_tasks/user_to_configure.yaml
    - import_tasks: shared_tasks/well_known_paths.yaml

    - name: Get the USB mountpoint
      ansible.builtin.command: lsblk -no mountpoint "/dev/{{ device }}1"
      register: usb_mnt
    
    #-- Ansible copy does not scale to recursive copies involving
    #-- hundreds/thousands of files, so we use rsync instead
    - name: Synchronize the files to the USB
      ansible.posix.synchronize:
        src: "{{ item.value.system_path }}/"
        dest: "{{ usb_mnt.stdout }}/{{ item.value.usb_path }}/"
      delegate_to: localhost
      with_dict:
        - "{{ well_known_paths }}"
    
    - name: Sync the USB to ensure all data has been written (May take a few minutes)
      ansible.builtin.command: /usr/bin/sync

