---
- name: Manage iptables rules for offline systems
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:

    - name: Ensure iptables starts on boot and is running
      ansible.builtin.service:
        name: iptables
        state: started
        enabled: yes

    - name: Flush any existing rules so we define only what is expected
      ansible.builtin.iptables:
        chain: "{{ item }}"
        action: flush
      loop:
        - "INPUT"
        - "FORWARD"
        - "OUTPUT"

    - name: Block outgoing traffic 
      ansible.builtin.iptables:
        chain: OUTPUT
        policy: DROP
        state: present

    - name: Save iptables rules so they persist across boots
      ansible.builtin.command: "iptables-save"
