---

# TODO: install linux-kbuild based on the latest kernel installed
#
- name: Install an updated kernel
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - import_tasks: shared_tasks/user_to_configure.yaml
    - import_tasks: shared_tasks/well_known_paths.yaml

    - name: Remove unused kernel(s)
      ansible.builtin.command:
        cmd: "apt -y autoremove"
      tags:
        - online

    - name: Add bookworm-backports as an apt source
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: 'deb http://http.us.debian.org/debian bookworm-backports main non-free-firmware'
        insertbefore: "BOF"
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Add bookworm-backports preference config
      ansible.builtin.template:
        src: "templates/bookworm-backports.j2"
        dest: "/etc/apt/preferences.d/bookworm-backports"
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Update apt sources to include bookworm-backports and preferences
      ansible.builtin.apt:
        update_cache: true
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Clear out any existing package list
      set_fact:
        all_packages: []

    - name: Add kernel and firmware packages to be installed
      set_fact:
        all_packages: "{{ all_packages | default([]) + [ item ] }}"
      with_items:
        - "{{ kernel_and_firmware_packages | default([]) }}"

    - name: Use the apt role to download or install as required
      ansible.builtin.import_role:
        name: apt
      tags:
        - online

    - name: Remove bookworm-backports as an apt source
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: 'deb http://http.us.debian.org/debian bookworm-backports main non-free-firmware'
        state: absent
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Remove bookworm-backports preferences config
      ansible.builtin.file:
        path: /etc/apt/preferences.d/bookworm-backports
        state: absent
      when: apt_snapshot_date is not defined
      tags:

    - name: Update apt sources to remove bookworm-backports
      ansible.builtin.apt:
        update_cache: true
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Remove unused kernel(s)
      ansible.builtin.command:
        cmd: "apt -y autoremove"
      tags:
        - online
