---

# This playbook has two approaches to kernel upgrades
# The older approach adds the bookworm-backports repo and explicitly pulls
# the latest kernel packages and dependencies. Those would typically come
# from the backports repo, but it is possible for some to come from the
# security repo, so lots of extra work has gone into making that work. This
# approach did not include firmware packages which led to increasing version
# drift and lacked support for newer hardware models.
#
# The new approach adds in firmware packages. Rather than continuing to
# manage everything manually/explicitly (which will be increasingly complex),
# apt preferences are now used. A preference config is defined for the list
# of kernel and firmware packages to upgrade, and the backports repo is
# given the same weight as stable and security. Apt then makes the necessary
# decisions to pull the latest versions and related dependencies. After the
# upgrades are completed, backports is removed so later package installs do
# not use that repo.
#
# The determining factor for which approach is used is the existence of
# the "kernel_and_firmware_packages" list variable. If it's defined, the
# new approach is used. If not, the old approach will be used to support
# older builds.
#
- name: Install an updated kernel
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - import_tasks: shared_tasks/user_to_configure.yaml
    - import_tasks: shared_tasks/well_known_paths.yaml

    - name: Remove unused kernel(s)
      ansible.builtin.command:
        cmd: "apt -y autoremove"
      tags:
        - online

    - name: Add bookworm-backports as an apt source
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: 'deb http://http.us.debian.org/debian bookworm-backports main non-free-firmware'
        insertbefore: "BOF"
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Add bookworm-backports preference config
      ansible.builtin.template:
        src: "templates/bookworm-backports-kernel-pref.j2"
        dest: "/etc/apt/preferences.d/bookworm-backports-kernel-pref"
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Update apt sources to include bookworm-backports
      ansible.builtin.apt:
        update_cache: true
      when: apt_snapshot_date is not defined
      tags:
        - online

    # Old approach
    - name: Kernel upgrade
      ansible.builtin.include_tasks: kernel_upgrade.yaml
      when: kernel_and_firmware_packages is not defined
    # End old approach

    # New approach
    - name: Kernel and firmware upgrades
      ansible.builtin.include_tasks: kernel_and_firmware_upgrade.yaml
      when: kernel_and_firmware_packages is defined
    # End new approach

    - name: Remove bookworm-backports as an apt source
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: 'deb http://http.us.debian.org/debian bookworm-backports main non-free-firmware'
        state: absent
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Remove bookworm-backports preferences config
      ansible.builtin.file:
        path: /etc/apt/preferences.d/bookworm-backports-kernel-pref
        state: absent
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Update apt sources to remove bookworm-backports
      ansible.builtin.apt:
        update_cache: true
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Remove unused kernel(s)
      ansible.builtin.command:
        cmd: "apt -y autoremove"
      tags:
        - online
