---

# TODO: install linux-kbuild based on the latest kernel installed
#
- name: Install an updated kernel
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - import_tasks: shared_tasks/user_to_configure.yaml
    - import_tasks: shared_tasks/well_known_paths.yaml

    - name: Add bookworm-backports as an apt source
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: 'deb http://http.us.debian.org/debian bookworm-backports main'
        insertbefore: "BOF"
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Update apt sources to include bookworm-backports
      ansible.builtin.apt:
        update_cache: true
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Download the kernel packages
      ansible.builtin.command:
        cmd: "apt-get install -y --reinstall --only-upgrade --no-install-recommends --download-only -t bookworm-backports {{ item }}"
      with_items:
        - "{{ kernel_packages | default([]) }}"
      tags:
        - online

    - name: Remove bookworm-backports as an apt source
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: 'deb http://http.us.debian.org/debian bookworm-backports main'
        state: absent
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Update apt sources to remove bookworm-backports
      ansible.builtin.apt:
        update_cache: true
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Install backported packages directly
      ansible.builtin.shell:
        cmd: "apt-get -y --no-install-recommends --only-upgrade install {{ item }}"
      with_items:
        - "{{ kernel_packages | default([]) }}"
      tags:
        - offline
