---

#TODO: Handle a locked down release where the kernel packages are
#      part of a VotingWorks aptly release instead of backports
#      Probably just a block condition based on existing of aptly release?
#
#TODO: dont hardcode to a debian backports release, make it a config var
#
- name: Install an updated kernel
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - import_tasks: shared_tasks/user_to_configure.yaml
    - import_tasks: shared_tasks/well_known_paths.yaml

    - name: Add bookworm-backports as an apt source
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: 'deb http://http.us.debian.org/debian bookworm-backports main'
      tags:
        - online

    - name: Update apt sources to include bookworm-backports
      ansible.builtin.apt:
        update_cache: true
      tags:
        - online

    - name: Download the kernel packages
      ansible.builtin.command:
        cmd: "apt-get install --reinstall --allow-downgrades --no-install-recommends --download-only -t bookworm-backports -y {{ item }}"
      with_items:
        - "{{ kernel_packages }}"
      tags:
        - online

    - name: Install the packages (batch)
      ansible.builtin.command:
        cmd: "apt-get install -y --allow-downgrades --no-install-recommends -t bookworm-backports {{ all_packages | join(' ') }}"
      tags:
        - offline

    - name: Remove bookworm-backports as an apt source
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: 'deb http://http.us.debian.org/debian bookworm-backports main'
        state: absent
      tags:
        - online

    - name: Delete the bookworm-backports preferences file
      ansible.builtin.file:
        path: /etc/apt/preferences.d/bookworm-backports
        state: absent
      tags:
        - online

    - name: Update apt sources to remove bookworm-backports
      ansible.builtin.apt:
        update_cache: true
      tags:
        - online
