---

# TODO: install linux-kbuild based on the latest kernel installed
#
- name: Install an updated kernel
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - import_tasks: shared_tasks/user_to_configure.yaml
    - import_tasks: shared_tasks/well_known_paths.yaml

    - name: Remove unused kernel(s)
      ansible.builtin.command:
        cmd: "apt -y autoremove"
      tags:
        - online

    - name: Add bookworm-backports as an apt source
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: 'deb http://http.us.debian.org/debian bookworm-backports main'
        insertbefore: "BOF"
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Update apt sources to include bookworm-backports
      ansible.builtin.apt:
        update_cache: true
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Get the latest linux-base version available in bookworm-backports or apt snapshot
      ansible.builtin.shell:
        cmd: "apt-cache madison linux-base | grep -E \"backports|{{ apt_snapshot_date | default('') }}\" | sort -k 3 -r | awk '{print $3}' | cut -d'|' -f1 | head -1"
      register: latest_linux_base_version
      tags:
        - online

    - name: Get the latest kernel version available in bookworm-backports or apt snapshot
      ansible.builtin.shell:
        cmd: "apt-cache madison linux-image-amd64 | grep -E \"backports|{{ apt_snapshot_date | default('') }}\" | sort -k 3 -r | awk '{print $3}' | cut -d'|' -f1 | head -1"
      register: latest_kernel_version
      tags:
        - online

    - name: Upgrade the kernel packages and dependencies
      ansible.builtin.command:
        cmd: "apt-get install -y --reinstall --install-suggests --no-install-recommends linux-base={{ latest_linux_base_version.stdout }} linux-image-amd64={{ latest_kernel_version.stdout }} 'linux-headers-{{ latest_kernel_version.stdout }}*deb12-amd64'"
      when: upgrade_kernel
      tags:
        - online

    - name: Remove bookworm-backports as an apt source
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: 'deb http://http.us.debian.org/debian bookworm-backports main'
        state: absent
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Update apt sources to remove bookworm-backports
      ansible.builtin.apt:
        update_cache: true
      when: apt_snapshot_date is not defined
      tags:
        - online

    - name: Remove unused kernel(s)
      ansible.builtin.command:
        cmd: "apt -y autoremove"
      tags:
        - online
