---

- name: Install system level dependencies used by various apps and services
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - name: Reload inventory from {{ inventory_dir }}
      include_vars:
        file: "{{ inventory_dir }}/group_vars/all/packages.yaml"
        name: original_package_list

    - name: Reload the package list
      set_fact:
        all_packages: "{{ original_package_list.all_packages | unique | select | list }}"

    - name: Import the apt role which supports online and offline builds
      ansible.builtin.import_role:
        name: apt
