---

- name: Install system level dependencies used by various apps and services
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - name: De-dupe the list for efficiency
      set_fact:
        all_packages: "{{ all_packages | unique | select | list }}"

    - name: Ensure snapshot repos are available
      ansible.builtin.blockinfile:
        path: /etc/apt/sources.list
        block: |
          deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/{{ apt_snapshot_date }}/ {{ release_name }} main non-free-firmware
          deb-src [check-valid-until=no] http://snapshot.debian.org/archive/debian/{{ apt_snapshot_date }}/ {{ release_name }} main non-free-firmware
          deb [check-valid-until=no] http://snapshot.debian.org/archive/debian-security/{{ apt_snapshot_date }}/ {{ release_name }}-security main non-free-firmware
          deb-src [check-valid-until=no] http://snapshot.debian.org/archive/debian-security/{{ apt_snapshot_date }}/ {{ release_name }}-security main non-free-firmware
      tags:
        - online

    - name: Refresh apt sources
      ansible.builtin.apt:
        update_cache: yes
      tags:
        - online

    - name: Import the apt role which supports online and offline builds
      ansible.builtin.import_role:
        name: apt
