---
- name: Prepare the USB for online phase export
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    #-- Not sure this needs an explicit online tag block but including for now
    - name: Block
      block: 
        - import_tasks: shared_tasks/usb_mgmt.yaml
          when: usb_disk_info is not defined
        
        #-- We need to be sure there aren't existing partitions/data 
        #-- So, check for any existing so we can remove in the next step
        - name: Get USB partition information
          community.general.parted: 
            device: "{{ usb_disk_path }}"
            unit: MiB
          register: usb_disk_info
        
        - name: Remove all partitions from USB
          community.general.parted:
            device: "{{ usb_disk_path }}"
            number: '{{ item.num }}'
            state: absent
          loop: '{{ usb_disk_info.partitions }}'
        
        - name: Create the partition
          community.general.parted:
            device: "{{ usb_disk_path }}"
            label: gpt
            name: 'VxTrustedBuild'
            number: 1
            part_start: 0MB
            part_end: "100%"
            fs_type: ext4
            state: present
        
        - name: Put a filesystem on the VxTrustedBuild partition
          filesystem:
            fstype: ext4
            dev: "/dev/{{device}}1"
            force: true
        
        #-- Label the partition for completeness
        - name: Create the primary label
          become: true
          command: e2label "/dev/{{ device }}1" VxTrustedBuild
        
      tags:
        - online
