---
- name: Manage firewalld rules for pollbook systems
  hosts: 127.0.0.1
  connection: local
  become: true

  #TODO: This is identical to firewalld, just with mesh0 added
  #      Possible candidate for future refactor/combine
  tasks:

    - name: Ensure firewalld starts on boot and is running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes

    - name: Allow localhost/loopback traffic
      ansible.builtin.command: "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 0 -o lo -j ACCEPT"

    - name: Allow mesh0 traffic
      ansible.builtin.command: "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 1 -o mesh0 -j ACCEPT"

    - name: Deny all other outgoing traffic
      ansible.builtin.command: "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 9 -j DROP"

    - name: Reload to save and apply changes
      ansible.builtin.command: "firewall-cmd --reload"
