---
- name: All the trusted build steps
  hosts: 127.0.0.1
  connection: local
  become: yes

- import_playbook: packages.yaml
- import_playbook: dev_packages.yaml
- import_playbook: initialize_encrypted_volumes.yaml
- import_playbook: node.yaml
- import_playbook: rust.yaml
- import_playbook: rubygems.yaml
- import_playbook: repos.yaml
