---

- name: Define the list of users to configure pulseaudio for
  ansible.builtin.set_fact:
    pulseaudio_users:
      - vx-vendor
      - vx-ui

- name: Look up each user
  ansible.builtin.command: "getent passwd {{ item }}"
  loop: "{{ pulseaudio_users }}"
  register: pulseaudio_getent_lookup
  changed_when: false
  failed_when: false

- name: Create systemd config directory for each user
  ansible.builtin.file:
    path: "{{ result.stdout.split(':')[5] }}/.config/systemd/user"
    state: directory
    owner: "{{ result.item }}"
    group: "{{ result.item }}"
    mode: 0644
    recurse: yes
  loop: "{{ pulseaudio_getent_lookup.results }}"
  loop_control:
    loop_var: result
    label: "{{ result.item }}"
  when: result.rc == 0

- name: Disable pulseaudio.service for each user
  ansible.builtin.file:
    src: /dev/null
    dest: "{{ result.stdout.split(':')[5] }}/.config/systemd/user/pulseaudio.service"
    state: link
    force: yes
  loop: "{{ pulseaudio_getent_lookup.results }}"
  loop_control:
    loop_var: result
    label: "{{ result.item }}"
  when: result.rc == 0

- name: Disable pulseaudio.socket for each user
  ansible.builtin.file:
    src: /dev/null
    dest: "{{ result.stdout.split(':')[5] }}/.config/systemd/user/pulseaudio.socket"
    state: link
    force: yes
  loop: "{{ pulseaudio_getent_lookup.results }}"
  loop_control:
    loop_var: result
    label: "{{ result.item }}"
  when: result.rc == 0

- name: Debug pulseaudio getent
  ansible.builtin.debug:
    var: pulseaudio_getent_lookup
