---
- name: Manage rsyslog/syslog configs
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:

    - name: Copy the VotingWorks rsyslog template into place
      ansible.builtin.copy:
        src: "files/votingworks-rsyslog-template.conf"
        dest: "/etc/rsyslog.d/30-votingworks.conf"

    - name: Copy the main VotingWorks rsyslog config into place
      ansible.builtin.copy:
        src: "files/rsyslog.conf"
        dest: "/etc/rsyslog.conf"

    - name: Copy the main VotingWorks journald config into place
      ansible.builtin.copy:
        src: "files/journald.conf"
        dest: "/etc/systemd/journald.conf"

    # This should be taken care of in the logrotate playbook
    # but it's included here in case this runs before/without that
    - name: Create votingworks log directory
      ansible.builtin.file:
        path: '/var/log/votingworks'
        state: directory
        owner: syslog
        group: adm
        mode: 0755

    - name: Restart the rsyslog service
      ansible.builtin.service:
        name: rsyslog
        state: restarted
