---
#-- NOTE: Rust uses gpg for verification of the downloaded installer
#-- We'll be using that rather than checksums in this playbook
- name: Trusted Build Install of Rust
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:

    - import_tasks: shared_tasks/user_to_configure.yaml
    - import_tasks: shared_tasks/well_known_paths.yaml


    - name: Define downloads_directory from well_known_paths
      set_fact:
        downloads_directory: "{{ well_known_paths['tools']['system_path'] }}"

    - name: Determine system architecture for appropriate Rust install
      set_fact: 
        architecture: "{{ 'aarch64' if (ansible_architecture == 'aarch64' or ansible_architecture == 'arm64') else 'x86_64' if (ansible_architecture == 'x86_64') else 'unsupported' }}"

    - name: Define the URL to download the appropriate Rust tarball
      set_fact:
        rust_tarball_url: "https://static.rust-lang.org/dist/rust-{{ rust_version }}-{{ architecture }}-unknown-linux-gnu.tar.gz"
      tags:
        - online

    - name: Define URL to Rust signing key
      set_fact:
        rust_signing_key_url: "https://static.rust-lang.org/rust-key.gpg.ascii"
      tags:
        - online

    - name: Override user if local_user is defined
      set_fact:
        user_to_configure: "{{ local_user }}"
      when: (local_user is defined) and (local_user|length > 0)

    - name: Download Rust
      ansible.builtin.get_url:
        url: "{{ rust_tarball_url }}"
        dest: "{{ downloads_directory }}/rust-{{ rust_version }}-{{ architecture }}-unknown-linux-gnu.tar.gz"
      tags:
        - online

    - name: Download Rust signing key
      ansible.builtin.get_url:
        url: "{{ rust_signing_key_url }}"
        dest: "{{ downloads_directory }}/rust-key.gpg.ascii"
      tags:
        - online

    - name: Check for a valid signature and exit if it fails
      ansible.builtin.shell: 
        cmd: "/usr/bin/gpg --verify {{ downloads_directory }}/rust-key.gpg.ascii {{ downloads_directory }}/rust-{{ rust_version }}-{{ architecture }}-unknown-linux-gnu.tar.gz"
      register: rust_signature_check
      failed_when: rust_signature_check.rc != 0

    - name: Extract Rust to tmp
      ansible.builtin.unarchive:
        src: "{{ downloads_directory }}/rust-{{ rust_version }}-{{ architecture }}-unknown-linux-gnu.tar.gz"
        dest: /var/tmp
        remote_src: yes
      become: true
      become_user: "{{ user_to_configure }}"
      tags:
        - offline

    - name: Install Rust {{ rust_version }} as {{ user_to_configure }}
      ansible.builtin.shell:
        cmd: "./install.sh --prefix=~{{ user_to_configure }}/.cargo "
        chdir: "/var/tmp/rust-{{ rust_version }}-{{ architecture }}-unknown-linux-gnu"
      become: true
      become_user: "{{ user_to_configure }}"
      tags:
        - offline

    - name: Ensure Rust is in {{ user_to_configure }} path
      ansible.builtin.lineinfile:
        path: "~{{ user_to_configure }}/.bashrc"
        line: 'PATH=$HOME/.cargo/bin:$PATH'
      tags:
        - offline
