---

- name: Perform shallow clone as {{ user_to_configure }}
  become: true
  become_user: "{{ user_to_configure }}"
  block:
    - name: Create code directory
      ansible.builtin.file:
        path: "{{ download_code_directory }}/{{ repo.key }}"
        state: directory

    - name: Initialize the git repo
      ansible.builtin.command:
        cmd: git init
        chdir: "{{ download_code_directory }}/{{ repo.key }}"
        creates: "{{ download_code_directory }}/{{ repo.key }}.git"

    - name: Add the remote origin
      ansible.builtin.command:
        cmd: "git remote add origin https://github.com/votingworks/{{ repo.key }}.git"
        chdir: "{{ download_code_directory }}/{{ repo.key }}"

    - name: Get the current commit
      ansible.builtin.command:
        cmd: git rev-parse HEAD
        chdir: "{{ download_code_directory }}/{{ repo.key }}"

    - name: Shallow commit fetch
      ansible.builtin.command:
        cmd: "git fetch --depth 1 origin {{ repo.value.version }}"
        chdir: "{{ download_code_directory }}/{{ repo.key }}"

    - name: Check out the fetched commit
      ansible.builtin.command:
        cmd: git checkout FETCH_HEAD
        chdir: "{{ download_code_directory }}/{{ repo.key }}"
