---

- name: Update cacvote printer configuration
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - name: Stop the cups service while config changes are made
      ansible.builtin.service:
        name: cups
        state: stopped

    - name: Specify the deviceURI for PJ-822
      ansible.builtin.lineinfile:
        path: "/etc/cups/printers.conf
        line: "DeviceURI usb://Brother/PJ-822"
        insertafter: 'MakeModel Brother PJ-822 CUPS'

    - name: Specify the deviceURI for QL-1100
      ansible.builtin.lineinfile:
        path: "/etc/cups/printers.conf
        line: "DeviceURI usb://Brother/QL-1100"
        insertafter: 'MakeModel Brother QL-1100 CUPS'

    - name: Start the cups service again
      ansible.builtin.service:
        name: cups
        state: started

