repos:
  vxsuite-complete-system:
    version: main
virt_image_path: "/var/lib/libvirt/images"
vm_name: "debian-12.1"
vm_disk_size_gb: 110
iso_name: "debian-12.1.0-amd64-netinst.iso"
iso_url: "http://cdimage.debian.org/cdimage/archive/12.1.0/arm64/iso-cd"
vm_preseed_path: "/home/{{ ansible_env.SUDO_USER }}/code/vxsuite-build-system/preseeds"
vm_preseed_file: "production-preseed.cfg"
secure_boot: true
rust_version: "1.72.0"
cloned_images:
  - online
  - offline
