---
batch_package_install: true

all_packages:
  - alsa-utils=1.2.8-1
  - brightnessctl=0.5.1-3
  - build-essential=12.9
  - cryptsetup=2:2.6.1-4~deb12u1
  - cups=2.4.2-3+deb12u1
  - cups-bsd=2.4.2-3+deb12u1
  - cups-client=2.4.2-3+deb12u1
  - curl=7.88.1-10+deb12u1
  - default-jdk=2:1.17-74
  - dosfstools=4.2-1
  - efitools=1.9.2-3
  - exfatprogs=1.2.0-1
  - fdisk=2.38.1-5+b1
  - firewalld=1.3.0-1
  - git=1:2.39.2-1.1
  - gvfs=1.50.3-1
  - gzip=1.12-1
  - iptables=1.8.9-2
  - kde-cli-tools=4:5.27.5.1-2
  - libatspi2.0-0=2.46.0-5
  - libcairo2-dev=1.16.0-7
  - libgif-dev=5.2.1-2.5
  - libglib2.0-bin=2.74.6-2
  - libgtk-3-0=3.24.37-2
  - libjpeg-dev=1:2.1.5-2
  - libnotify4=0.8.1-1
  - libpango1.0-dev=1.50.12+ds-1
  - libpcsclite1=1.9.9-2
  - libpcsclite-dev=1.9.9-2
  - libpixman-1-dev=0.42.2-1
  - libpng-dev=1.6.39-2
  - libsane=1.2.1-2
  - libudev-dev=252.12-1~deb12u1
  - libusb-1.0-0-dev=2:1.0.26-1
  - libx11-dev=2:1.8.4-2+deb12u1
  - libxss1=1:1.2.3-1
  - libxtst6=2:1.2.3-1.1
  - libzbar-dev=0.23.92-7
  - make=4.3-4.1
  - mingetty=1.08-4
  - openbox=3.6.1-10
  - parted=3.5-3
  - pcscd=1.9.9-2
  - pcsc-tools=1.6.2-1
  - pulseaudio=16.1+dfsg1-2+b1
  - pulseaudio-utils=16.1+dfsg1-2+b1
  - rsync=3.2.7-1
  - rsyslog=8.2302.0-1
  - ruby=1:3.1
  - sbsigntool=0.9.4-3.1
  - swig=4.1.0-0.2
  - tar=1.34+dfsg-1.2
  - trash-cli=0.17.1.14-5
  - unclutter=8-25
  - unzip=6.0-28
  - wget=1.21.3-1+b2
  - x11-common=1:7.7+23
  - xdg-utils=1.1.3-4.1
  - xinit=1.4.0-1
  - xinput=1.6.3-1
  - xorg=1:7.7+23
  - xserver-xorg-core=2:21.1.7-3
  - xserver-xorg-input-all=1:7.7+23
  - xserver-xorg-video-all=1:7.7+23
  - zip=3.0-13

tpm_packages:
  - autoconf=2.71-3
  - autoconf-archive=20220903-3
  - automake=1:1.16.5-1.3
  - autotools-dev=20220109.1
  - libcurl4-openssl-dev=7.88.1-10+deb12u1
  - libjson-c-dev=0.16-2
  - libltdl-dev=2.4.7-5
  - libqrencode4=4.1.1-1
  - libqrencode-dev=4.1.1-1
  - libssl-dev=3.0.9-1
  - libtool=2.4.7-5
  - libtss2-esys-3.0.2-0=3.2.1-3
  - libtss2-fapi1=3.2.1-3
  - libtss2-mu0=3.2.1-3
  - libtss2-rc0=3.2.1-3
  - libtss2-sys1=3.2.1-3
  - libtss2-tcti-cmd0=3.2.1-3
  - libtss2-tcti-device0=3.2.1-3
  - libtss2-tctildr0=3.2.1-3
  - libtss2-tcti-mssim0=3.2.1-3
  - libtss2-tcti-swtpm0=3.2.1-3
  - m4=1.4.19-3
  - qrencode=4.1.1-1
  - tpm2-openssl=1.1.1-1
  - tpm2-tools=5.4-1
