---
enable_networking: true

networking_packages:
  - avahi-daemon
  - avahi-utils
  - strongswan-swanctl
  - libstrongswan-extra-plugins
  - libstrongswan-standard-plugins
  - charon-systemd
  - strongswan-pki
  - avahi-autoipd
  - iw
