---
batch_package_install: true

all_packages:
  - alsa-utils
  - brightnessctl
  - build-essential
  - cryptsetup
  - cups
  - cups-bsd
  - cups-client
  - curl
  - default-jdk
  - dosfstools
  - efitools
  - exfatprogs
  - fdisk
  - firewalld
  - git
  - gvfs
  - gzip
  - iptables
  - kde-cli-tools
  - libatspi2.0-0
  - libcairo2-dev
  - libgif-dev
  - libglib2.0-bin
  - libgtk-3-0
  - libjpeg-dev
  - libnotify4
  - libpango1.0-dev
  - libpcsclite1
  - libpcsclite-dev
  - libpixman-1-dev
  - libpng-dev
  - libsane
  - libudev-dev
  - libusb-1.0-0-dev
  - libx11-dev
  - libxss1
  - libxtst6
  - libzbar-dev
  - make
  - mingetty
  - openbox
  - parted
  - pcscd
  - pcsc-tools
  - pulseaudio
  - pulseaudio-utils
  - rsync
  - rsyslog
  - ruby
  - sbsigntool
  - swig
  - tar
  - trash-cli
  - unclutter
  - unzip
  - wget
  - x11-common
  - xdg-utils
  - xinit
  - xinput
  - xorg
  - xserver-xorg-core
  - xserver-xorg-input-all
  - xserver-xorg-video-all
  - zip

tpm_packages:
  - autoconf
  - autoconf-archive
  - automake
  - autotools-dev
  - libcurl4-openssl-dev
  - libjson-c-dev
  - libltdl-dev
  - libqrencode4
  - libqrencode-dev
  - libssl-dev
  - libtool
  - libtss2-esys-3.0.2-0
  - libtss2-fapi1
  - libtss2-mu0
  - libtss2-rc0
  - libtss2-sys1
  - libtss2-tcti-cmd0
  - libtss2-tcti-device0
  - libtss2-tctildr0
  - libtss2-tcti-mssim0
  - libtss2-tcti-swtpm0
  - m4
  - qrencode
  - tpm2-openssl
  - tpm2-tools
  - tpm-udev
