repos:
  kiosk-browser:
    version: e42a0607f9e16112a88a8c726d7b059479ed7ff4
  cacvote:
    version: main
  vxsuite-complete-system:
    version: main
virt_image_path: "/var/lib/libvirt/images"
vm_name: "debian12-2-cacvote-base"
vm_disk_size_gb: 50
iso_version: "12.2.0"
iso_name: "debian-{{ iso_version }}-amd64-netinst.iso"
iso_url: "https://cdimage.debian.org/cdimage/archive/{{ iso_version }}/amd64/iso-cd"
vm_preseed_path: "/home/{{ ansible_env.SUDO_USER }}/code/vxsuite-build-system/preseeds"
vm_preseed_file: "cacvote-prod-preseed.cfg"
secure_boot: true
cloned_images:
  - cacvote
