- name: Clone base vm to another
  hosts: localhost
  become: yes

  tasks:

    - name: See if the {{ vm_clone_name }} VM already exists
      shell:
        cmd: virsh dominfo {{ vm_clone_name }}
      register: does_vm_exist
      changed_when: no
      ignore_errors: true

    - name: Clone VM
      command: >
        virt-clone 
        -o {{ vm_name }} 
        -n {{ vm_clone_name }} 
        --auto-clone 
        --check disk_size=off
      register: clone_status
      when: does_vm_exist.rc != 0

   #- name: Generate keypair
     #community.crypto.openssh_keypair:
       #path: /tmp/id_rsa
       #size: 2048
       #become: true
       #become_user: "vx"

   #- debug:
      #var: clone_status

   #- name: Inject the ssh key for future access
     #command: >
       #virt-sysprep
       #-a {{ image_path }}/{{ vm_clone_name }}.qcow2
       #--ssh-inject vx:file:/tmp/id_rsa.pub
       #--run-command 'cd /etc/ssh; ssh-keygen -A'
     #when: does_vm_exist.rc == 0 or clone_status.rc == 0


