---     
- name: Configure the rust environment for a user
  hosts: 127.0.0.1
  connection: local
  become: true

  vars:
    user_to_configure: "{{ ansible_env.SUDO_USER | default('root') }}"
    rustup_home: "/usr/local/rustup"
    cargo_env: "/usr/local/cargo"

  tasks:

    - name: Override user if local_user is defined
      set_fact:
        user_to_configure: "{{ local_user }}"
      when: (local_user is defined) and (local_user|length > 0)

    #-- This should be configured automatically by Rust, but add if not
    - name: Ensure we source the global cargo ENV for {{ user_to_configure }}
      ansible.builtin.lineinfile:
        path: "~{{ user_to_configure }}/.bashrc"
        line: '. "$HOME/.cargo/env"'

