---
- name: Create Local Dev User
  hosts: 127.0.0.1
  connection: local
  become: true

  vars:
    cargo_home: "/usr/local/cargo"

  tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ local_user }}"
        shell: "/bin/bash"
        password: "{{ 'changeme' | password_hash('sha512') }}"
        append: true
        groups: "lpadmin"
        state: present
      when: (local_user is defined) and (local_user|length > 0) 

    - name: Grant full sudo to user
      community.general.sudoers:
        name: "{{ local_user }}"
        state: present
        user: "{{ local_user }}"
        commands: ALL
      when: (local_user is defined) and (local_user|length > 0) 

    - name: Ensure /usr/sbin is part of PATH
      ansible.builtin.lineinfile:
        path: "~{{ local_user }}/.bashrc"
        line: "export PATH=$PATH:/usr/sbin"
      when: (local_user is defined) and (local_user|length > 0)

    - name: Set Rustup path
      ansible.builtin.lineinfile:
        path: "~{{ local_user }}/.bashrc"
        line: "export RUSTUP_HOME=/usr/local/rustup"
      when: (local_user is defined) and (local_user|length > 0)

    - name: Set Rust Cargo path
      ansible.builtin.lineinfile:
        path: "~{{ local_user }}/.bashrc"
        line: "export CARGO_HOME=/usr/local/cargo"
      when: (local_user is defined) and (local_user|length > 0)

    - name: Ensure we source the global cargo ENV
      ansible.builtin.lineinfile:
        path: "~{{ local_user }}/.bashrc"
        line: ". {{ cargo_home }}/env"
      when: (local_user is defined) and (local_user|length > 0)
