---
- name: Install Rust
  hosts: 127.0.0.1
  connection: local
  become: true

  vars:
    rust_version: '1.68.0'
    rustup_home: '/usr/local/rustup'
    cargo_home: '/usr/local/cargo'
    rustup_install_url: 'https://sh.rustup.rs'
    rustup_install_cmd: '/tmp/rustup.sh'

  tasks:

    - name: Download rustup
      ansible.builtin.get_url:
        url: "{{ rustup_install_url }}"
        dest: "{{ rustup_install_cmd }}"

    - name: Install Rust {{ rust_version }}
      ansible.builtin.shell:
        cmd: "cat {{ rustup_install_cmd }} | RUSTUP_HOME={{ rustup_home }} CARGO_HOME={{ cargo_home }} sh -s -- --default-toolchain {{ rust_version }} -y"

