---
- name: Install Rust
  hosts: 127.0.0.1
  connection: local

  vars:
    rust_version: '1.68.0'
    user_to_configure: "{{ ansible_env.SUDO_USER | default('root') }}"
    rustup_install_url: 'https://sh.rustup.rs'
    rustup_install_cmd: '/tmp/rustup.sh'

  tasks:

    - name: Override user if local_user is defined
      set_fact:
        user_to_configure: "{{ local_user }}"
      when: (local_user is defined) and (local_user|length > 0)

    - name: Download rustup
      ansible.builtin.get_url:
        url: "{{ rustup_install_url }}"
        dest: "{{ rustup_install_cmd }}"
      become: true
      become_user: "{{ user_to_configure }}"

    #-- Runs as user_to_configure
    - name: Install Rust {{ rust_version }}
      ansible.builtin.shell:
        cmd: "cat {{ rustup_install_cmd }} | sh -s -- --default-toolchain {{ rust_version }} -y"
      become: true
      become_user: "{{ user_to_configure }}"

    #-- This should be configured automatically by Rust, but add if not
    - name: Ensure we source the global cargo ENV for {{ user_to_configure }}
      ansible.builtin.lineinfile:
        path: "~{{ user_to_configure }}/.bashrc"
        line: '. "$HOME/.cargo/env"'
